# Generated by Django 5.0.3 on 2024-08-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_product_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catgory_id',
            new_name='category_id',
        ),
    ]
